#!/bin/bash

#our program goal is to install mysql

USERID=$(id -u)

if [ $USERID -ne 0 ]
then 
    echo "ERROR:: please run this script with root access"
    exit 1
fi    
#it is our responsibility again to check installion is success or not
yum install mysql -y

if [ $? -ne 0 ]
then 
    echo "installion of mysql is error"
    exit 1  
else
    echo "installation of mysql is success"
if        

yum install postifx -y

if [ $? -ne 0 ]
then 
    echo"installion of postfix is error"
    exit 1
else
    echo "installion of postfix is success"
if    